baseURL = "https://helloa24.com/blog/"
languageCode = "ja-jp"
title = "My New Hugo Site"
theme = "Memorandum"

sCJKLanguage = true

copyright = "&copy; 2018 Atsushi Hori"
disqusShortname = ""               # DISQUSでユーザー登録、Adminから新規サイトを作ってそのショートネームを設定
#googleAnalytics = ""               # google Analyticsの追跡タグ 追跡が要らなかったら行ごと削除
summarylength = 200                # トップページの記事一覧の要約文字数(英語の場合単語数)

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "メモにメモ以上の価値を求めるのはいけない"  # 必須 サイトの副題
keywords = "数理最適化,オペレーションズ・リサーチ,Atsushi Hori"   # SEO用キーワード
author = "Atsushi Hori" # 必須
profile = "自己紹介を書いて" # 必須
displayauthor = false # 記事自体に書いた人を表示するかどうか
DateForm = "2006-01-02" # 日付の書式( https://gohugo.io/functions/dateformat/ )

[params.highlight]
theme = "monokai-sublime" # highlight.jsのテーマ名 必須

[[params.social]]
url = "https://github.com/Keith-Campbell"   # Githubアカウント
fa_icon_class = "fab fa-github"
