baseURL = "https://helloa24.com/blog/"
languageCode = "ja-jp"
title = "Planetarium"
theme = "Memorandum"

sCJKLanguage = true

copyright = "&copy; 2018 A24H"
disqusShortname = ""               # DISQUSでユーザー登録、Adminから新規サイトを作ってそのショートネームを設定
#googleAnalytics = ""               # google Analyticsの追跡タグ 追跡が要らなかったら行ごと削除
summarylength = 50                # トップページの記事一覧の要約文字数(英語の場合単語数)

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "技術メモ（最適化数学関連）兼日記です"  # 必須 サイトの副題
keywords = ["数理最適化" , "オペレーションズ・リサーチ"]   # SEO用キーワード
author = "A24H" # 必須
profile = "京都の大学院生（情報系の応用数学）です．研究の傍趣味としてウェブサイトをやってます．ウェブサイト開発に関してはど初心者ですが，新たに気づいたことを書きます．他にも，大学院修士課程まで専門としていた数理最適化に関する記事も書きます．" # 必須
displayauthor = false # 記事自体に書いた人を表示するかどうか
DateForm = "2006-01-02" # 日付の書式( https://gohugo.io/functions/dateformat/ )

[params.highlight]
theme = "monokai-sublime" # highlight.jsのテーマ名 必須

[[params.social]]
url = "https://github.com/Keith-Campbell"   # Githubアカウント
fa_icon_class = "fab fa-github"
